apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-prometheus-stack
  project: default
  source:
    path: helm
    repoURL: https://github.com/stratolinux/argo-helm-repo.git
    targetRevision: HEAD
    helm:
      valuesObject:
        prometheus:
          ingress:
            enabled: true
            hosts: ["your.host.name"]
          namespace: kube-prometheus-stack
          adminPassword: "adminpassword"
        traefik:
          namespace: traefik
          cloudflare:
            cf_api_email: cf_api_email
            cf_dns_api_token: cf_dns_api_token
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
