apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.prometheus.namespace }}
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "61.1.1"
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        grafana:
          adminPassword: {{ .Values.prometheus.adminPassword }}
          ingress:
            enabled: {{ .Values.prometheus.ingress.enabled }}
            hosts: {{ .Values.prometheus.ingress.hosts }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
