---
# traefik helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: "4.6.0"
    chart: csi-driver-nfs
    helm:
      valuesObject:
        controller.runOnControlPlane: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: storage.k8s.io
      kind: CSIDriver
      jqPathExpressions:
        - .spec.seLinuxMount
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfsclass
provisioner: nfs.csi.k8s.io   
parameters:
  server: {{ .Values.csinfs.host }}
  share: {{ .Values.csinfs.share }}
  subDir: ${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nolock
