---
# traefik helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-smb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: "v1.14.0"
    chart: csi-driver-smb
    helm:
      valuesObject:
        controller.runOnControlPlane: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

