---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.volsync.namespace }}
---
# volsync helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.volsync.namespace }}
  project: default
  source:
    repoURL: https://backube.github.io/helm-charts
    targetRevision: "0.9.1"
    chart: volsync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
---
apiVersion: v1
kind: Secret
type: Opaque     
metadata:
  name: volsync-rclone-secret
  namespace: {{ .Values.volsync.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  rclone.conf: |
    [minio]
    type = s3
    provider = Minio
    env_auth = false
    endpoint = {{ .Values.volsync.endpoint }}
    acl = bucket-owner-full-control
    access_key_id = {{ .Values.replication.aws_access_key_id }}
    secret_access_key = {{ .Values.replication.aws_secrey_access_key }}
