apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: {{ .Values.traefik.namespace }}
data:
  CF_API_EMAIL: {{ .Values.traefik.cf_api_email }}
  CF_DNS_API_TOKEN: {{ .Values.traefik.cf_dns_api_token }}

