# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replication settings, identical for all services
replication:
  enabled: true
  restic_repository: "s3:http://minio.local:9000"
  restic_password: "restic_password"
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

# homepage
homepage:
  enabled: true
  image: "ghcr.io/gethomepage/homepage"
  version: "v0.8.11"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "homepage.local"
  namespace: media
  configPVC: "config-pvc-will-create-if-needed"

# navidrome 
navidrome:
  enabled: true
  image: "deluan/navidrome"
  version: "0.51.1"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "navidrome.local"
  namespace: media
  media:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  configPVC: "config-pvc-will-create-if-needed"

# posterr
posterr:
  enabled: true
  image: "petersem/posterr"
  version: "latest"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "posterr.local"
  namespace: media
  configPVC: "config-pvc-will-create-if-needed"

# whisparr
whisparr:
  enabled: true
  image: "ghcr.io/hotio/whisparr"
  version: "latest"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "whisparr.local"
  namespace: media
  media:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  services:
    share: "//smb.server.name/share2"
    secret: "name-of-secret-with-creds2"
    secretNamespace: "namespace-holding-secret2"
  configPVC: "config-pvc-will-create-if-needed"

# audiobookshelf
audiobookshelf:
  enabled: true
  image: "ghcr.io/advplyr/audiobookshelf"
  version: "2.8.1"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "audiobookshelf.local"
  namespace: media
  books:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  podcasts:
    share: "//smb.server.name/share2"
    secret: "name-of-secret-with-creds2"
    secretNamespace: "namespace-holding-secret2"
  configPVC: "config-pvc-will-create-if-needed"
  metadataPVC: "config-pvc-will-create-if-needed"