# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replication settings, identical for all services
replication:
  enabled: true
  restic_repository: "s3:http://minio.local:9000"
  restic_password: "restic_password"
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

# homepage
homepage:
  enabled: false
  image: "ghcr.io/gethomepage/homepage"
  version: "v0.8.11"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "homepage.local"
  namespace: media
  configPVC: "homepage-config"

# navidrome 
navidrome:
  enabled: false
  image: "deluan/navidrome"
  version: "0.51.1"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "navidrome.local"
  namespace: media
  media:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  configPVC: "navidrome-config"

# posterr
posterr:
  enabled: false
  image: "petersem/posterr"
  version: "latest"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "posterr.local"
  namespace: media
  configPVC: "posterr-config"

# maintainerr
maintainerr:
  enabled: false
  image: "ghcr.io/jorenn92/maintainerr"
  version: "latest"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "maintainerr.local"
  namespace: media
  configPVC: "maintainerr-config"

# whisparr
whisparr:
  enabled: false
  image: "ghcr.io/hotio/whisparr"
  version: "latest"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "whisparr.local"
  namespace: media
  media:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  services:
    share: "//smb.server.name/share2"
    secret: "name-of-secret-with-creds2"
    secretNamespace: "namespace-holding-secret2"
  configPVC: "whisparr-config"

# audiobookshelf
audiobookshelf:
  enabled: false
  image: "ghcr.io/advplyr/audiobookshelf"
  version: "2.8.1"
  replicationSchedule: "0 * * * *"
  ingress:
    enabled: true
    host: "audiobookshelf.local"
  namespace: media
  books:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  podcasts:
    share: "//smb.server.name/share2"
    secret: "name-of-secret-with-creds2"
    secretNamespace: "namespace-holding-secret2"
  configPVC: "audiobookshelf-config"
  metadataPVC: "audiobookshelf-metadata"

# tubesync
tubesync:
  enabled: false
  image: "ghcr.io/meeb/tubesync"
  version: "latest"
  replicationSchedule: "30 * * * *"
  ingress:
    enabled: true
    host: "tubesync.local"
  namespace: media
  videos:
    share: "//smb.server.name/share"
    secret: "name-of-secret-with-creds"
    secretNamespace: "namespace-holding-secret"
  configPVC: "tubesync-config"
