{{ if .Values.audiobookshelf.enabled }}
---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.audiobookshelf.namespace }}
  annotations:
    volsync.backube/privileged-movers: "true"
---
# config Replication Bucket
{{ if .Values.replication.enabled }}
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: {{ .Values.environment }}-{{ .Values.audiobookshelf.namespace }}-audiobookshelf-config
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  deletionPolicy: Orphan
  forProvider: {}
  providerConfigRef:
    name: provider-minio
{{ end }}
---
# metadata Replication Bucket
{{ if .Values.replication.enabled }}
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: {{ .Values.environment }}-{{ .Values.audiobookshelf.namespace }}-audiobookshelf-metadata
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  deletionPolicy: Orphan
  forProvider: {}
  providerConfigRef:
    name: provider-minio
{{ end }}
---
# config Replication Secret
{{ if .Values.replication.enabled }}
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: audiobookshelf-bucket-config
  namespace: {{ .Values.audiobookshelf.namespace }}
stringData:
  RESTIC_REPOSITORY: {{ .Values.replication.restic_repository }}/{{ .Values.environment }}-{{ .Values.audiobookshelf.namespace }}-audiobookshelf-config
  RESTIC_PASSWORD: {{ .Values.replication.restic_password }}
  AWS_ACCESS_KEY_ID: {{ .Values.replication.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.replication.aws_secret_access_key }}
{{ end }}
---
# metadata Replication Secret
{{ if .Values.replication.enabled }}
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: audiobookshelf-bucket-metadata
  namespace: {{ .Values.audiobookshelf.namespace }}
stringData:
  RESTIC_REPOSITORY: {{ .Values.replication.restic_repository }}/{{ .Values.environment }}-{{ .Values.audiobookshelf.namespace }}-audiobookshelf-metadata
  RESTIC_PASSWORD: {{ .Values.replication.restic_password }}
  AWS_ACCESS_KEY_ID: {{ .Values.replication.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.replication.aws_secret_access_key }}
{{ end }}
---
# config ReplicationDestination
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: audiobookshelf-config-replication-destination
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  trigger:
    # manual restore
    manual: "seed-volume-from-backup"
  restic:
    # Name of the Secret with the connection information
    repository: audiobookshelf-bucket-config
    capacity: 5Gi
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
    accessModes:
      - ReadWriteOnce
{{ end }}
---
# config ReplicationSource
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: audiobookshelf-config-replication-source
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ .Values.audiobookshelf.configPVC }}
  trigger:
    # Take a backup per cron schedule
    schedule: {{ .Values.audiobookshelf.replicationSchedule }}
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: audiobookshelf-bucket-config
    # Retention policy for backups
    retain:
      hourly: 2
      daily: 2
      weekly: 2
      monthly: 2
      yearly: 1
    # just in case it was locked
    unlock: unlock-me
    # Snap the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: ceph-block
{{ end }}

---
# config ReplicationDestination
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: audiobookshelf-metadata-replication-destination
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  trigger:
    # manual restore
    manual: "seed-volume-from-backup"
  restic:
    # Name of the Secret with the connection information
    repository: audiobookshelf-bucket-metadata
    capacity: 5Gi
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
    accessModes:
      - ReadWriteOnce
{{ end }}
---
# config ReplicationSource
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: audiobookshelf-metadata-replication-source
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ .Values.audiobookshelf.metadataPVC }}
  trigger:
    # Take a backup per cron schedule
    schedule: {{ .Values.audiobookshelf.schedule }}
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: audiobookshelf-bucket-metadata
    # Retention policy for backups
    retain:
      hourly: 2
      daily: 2
      weekly: 2
      monthly: 2
      yearly: 1
    # just in case it was locked
    unlock: unlock-me
    # Snap the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: ceph-block
{{ end }}
---
# config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.audiobookshelf.configPVC }}
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
{{ if .Values.replication.enabled }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: audiobookshelf-config-replication-destination
{{ end }}
  resources:
    requests:
      storage: 5Gi
---
# metadata PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.audiobookshelf.metadataPVC }}
  namespace: {{ .Values.audiobookshelf.namespace }}
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
{{ if .Values.replication.enabled }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: audiobookshelf-metadata-replication-destination
{{ end }}
  resources:
    requests:
      storage: 5Gi
---
# PV for books share
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: audiobookshelf-books-share
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: {{ .Values.audiobookshelf.books.share }}##
    volumeAttributes:
      source: //{{ .Values.audiobookshelf.books.share }}
    nodeStageSecretRef:
      name: {{ .Values.audiobookshelf.books.secret }}
      namespace: {{ .Values.audiobookshelf.books.secretNamespace }}
---
### Claim for books share
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.audiobookshelf.namespace }}
  name: audiobookshelf-books-claim
spec:
  storageClassName: manual
  volumeName: audiobookshelf-books-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
# PV for podcasts share
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: audiobookshelf-podcasts-share
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: {{ .Values.audiobookshelf.podcasts.share }}##
    volumeAttributes:
      source: //{{ .Values.audiobookshelf.podcasts.share }}
    nodeStageSecretRef:
      name: {{ .Values.audiobookshelf.podcasts.secret }}
      namespace: {{ .Values.audiobookshelf.podcasts.secretNamespace }}
---
### Claim for podcasts share
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.audiobookshelf.namespace }}
  name: audiobookshelf-podcasts-claim
spec:
  storageClassName: manual
  volumeName: audiobookshelf-podcasts-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
# audiobookshelf helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.audiobookshelf.namespace }}
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: "3.1.0"
    chart: app-template
    helm:
      valuesObject:
        controllers:
          audiobookshelf:
            containers:
              app:
                image:
                  repository: {{ .Values.audiobookshelf.image }}
                  tag: {{ .Values.audiobookshelf.version }}
        service:
          app:
            controller: audiobookshelf
            ports:
              http:
                port: 80
        ingress:
          app:
            enabled: {{ .Values.audiobookshelf.ingress.enabled }}
            hosts:
              - host: {{ .Values.audiobookshelf.ingress.host }}
                paths:
                  - path: /
                    pathType: Prefix
                    service: 
                      name: audiobookshelf
                      port: 80
        persistence:
          config:
            enabled: true
            existingClaim: {{ .Values.audiobookshelf.configPVC }}
            globalMounts:
              - path: /config
          metadata:
            enabled: true
            existingClaim: {{ .Values.audiobookshelf.metadataPVC }}
            globalMounts:
              - path: /metadata
          books:
            enabled: true
            existingClaim: audiobookshelf-books-claim
            globalMounts:
              - path: /audiobooks
          podcasts:
            enabled: true
            existingClaim: audiobookshelf-podcasts-claim
            globalMounts:
              - path: /podcasts
        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}
