{{ if .Values.navidrome.enabled }}
---
# config Replication Secret
{{ if .Values.replication.enabled }}
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: navidrome-bucket-config
  namespace: {{ .Values.navidrome.namespace }}
stringData:
  RESTIC_REPOSITORY: {{ .Values.replication.restic_repository }}/{{ .Values.navidrome.namespace }}-navidrome-config
  RESTIC_PASSWORD: {{ .Values.replication.restic_password }}
  AWS_ACCESS_KEY_ID: {{ .Values.replication.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.replication.aws_secret_access_key }}
{{ end }}
---
# config ReplicationDestination
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: navidrome-config-replication-destination
  namespace: {{ .Values.navidrome.namespace }}
spec:
  trigger:
    # manual restore
    manual: "seed-volume-from-backup"
  restic:
    # Name of the Secret with the connection information
    repository: navidrome-bucket-config
    capacity: 5Gi
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
    accessModes:
      - ReadWriteOnce
{{ end }}
---
# config ReplicationSource
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: navidrome-config-replication-source
  namespace: {{ .Values.navidrome.namespace }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ .Values.navidrome.configPVC }}
  trigger:
    # Take a backup per cron schedule
    schedule: {{ .Values.navidrome.replicationSchedule }}
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: navidrome-bucket-config
    # Retention policy for backups
    retain:
      hourly: 2
      daily: 2
      weekly: 2
      monthly: 1
      yearly: 0
    # just in case it was locked
    unlock: unlock-me
    # Snap the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: ceph-block
{{ end }}
---
# config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.navidrome.configPVC }}
  namespace: {{ .Values.navidrome.namespace }}
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
{{ if .Values.replication.enabled }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: navidrome-config-replication-destination
{{ end }}
  resources:
    requests:
      storage: 5Gi
---
# PV for media share
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: navidrome-media-share
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: {{ .Values.navidrome.media.share }}##
    volumeAttributes:
      source: //{{ .Values.navidrome.media.share }}
    nodeStageSecretRef:
      name: {{ .Values.navidrome.media.secret }}
      namespace: {{ .Values.navidrome.media.secretNamespace }}
---
### Claim for media share
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.navidrome.namespace }}
  name: navidrome-media-claim
spec:
  storageClassName: manual
  volumeName: navidrome-media-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
# Navidrome helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.navidrome.namespace }}
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: "3.1.0"
    chart: app-template
    helm:
      valuesObject:
        controllers:
          navidrome:
            containers:
              app:
                image:
                  repository: {{ .Values.navidrome.image }}
                  tag: {{ .Values.navidrome.version }}
        service:
          app:
            controller: navidrome
            ports:
              http:
                port: 4533
        ingress:
          app:
            enabled: {{ .Values.navidrome.ingress.enabled }}
            hosts:
              - host: {{ .Values.navidrome.ingress.host }}
                paths:
                  - path: /
                    pathType: Prefix
                    service: 
                      name: navidrome
                      port: 4533
        persistence:
          data:
            enabled: true
            existingClaim: {{ .Values.navidrome.configPVC }}
            globalMounts:
              - path: /data
          music:
            enabled: true
            existingClaim: navidrome-media-claim
            globalMounts:
              - path: /music
        env:
          ND_SCANSCHEDULE: 1h
          ND_LOGLEVEL: info
          ND_SESSIONTIMEOUT: 24h
          ND_BASEURL: ""
        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}