# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# the default storage class to use
storageclass: longhorn

metallb:
  enabled: false
  namespace: metallb-system
  version: "v0.14.5"
  addresses:
    - 10.10.90.100-10.10.90.110

volsync:
  enabled: false
  namespace: volsync-system
  version: "0.9.1"
  endpoint: http://my.s3.provider:port/bucket
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

cert_manager:
  enabled: false
  version: "v1.14.5"

csismb:
  enabled: false
  version: "v1.14.0"
  username: user
  password: password
  share: smb.server.name/share

csinfs:
  enabled: false
  version: "v4.7.0"
  host: nfs.server.name
  share: /share

traefik:
  enabled: false
  version: "36.3.0"
  namespace: traefik
  configPVC: traefik
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
  loadBalancerIP: "0.0.0.0"
#  default_cert:
#    main: main.host.name

ceph:
  enabled: false
  namespace: rook-ceph
  dashPassword: myPassword
  ingress:
    host: myhostname.mydomain

longhorn:
  enabled: false
  version: "1.9.0"
  namespace: longhorn-system
  backup:
    location: "nfs://host.name:/export/path"
    secret: ""
  ingress:
    host: myhostname.mydomain
