# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

reflector:
  # -- flag to enable or disable the deployment of https://github.com/emberstack/kubernetes-reflector
  enabled: false

  # -- version of reflector helm chart from https://emberstack.github.io/helm-charts
  version: "9.1.22"

  # -- target namespace for reflector
  namespace: kube-system



cert_manager:
  enabled: false
  version: "v1.18.2"
  namespace: cert-manager
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
  issuer: "cloudflare-clusterissuer"
  default_certificate_secret: default-certificate-secret
  server: "staging"
  default_domains:
    - "my.domain"
    - "*.my.domain"

metallb:
  enabled: false
  namespace: metallb-system
  version: "v0.15.2"
  default_addresses:
    - 10.10.90.100-10.10.90.110
  # reserved address must be explicity requested in the service definition
  reserved_addresses:
    - 10.10.90.120/30

traefik:
  enabled: false
  version: "36.3.0"
  namespace: traefik

longhorn:
  enabled: false
  version: "1.9.0"
  namespace: longhorn-system
  backup:
    location: "nfs://host.name:/export/path"
    secret: ""
  ingress:
    host: myhostname.mydomain

# legacy stuff below
volsync:
  enabled: false
  namespace: volsync-system
  version: "0.9.1"
  endpoint: http://my.s3.provider:port/bucket
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

csismb:
  enabled: false
  version: "v1.14.0"
  username: user
  password: password
  share: smb.server.name/share

csinfs:
  enabled: false
  version: "v4.7.0"
  host: nfs.server.name
  share: /share

ceph:
  enabled: false
  namespace: rook-ceph
  dashPassword: myPassword
  ingress:
    host: myhostname.mydomain


