# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

reflector:
  enabled: false
  version: "9.1.22"
  namespace: kube-system

cert_manager:
  enabled: false
  version: "v1.18.2"
  namespace: cert-manager
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
  issuer: "cloudflare-clusterissuer"
  default_certificate_secret: default-certificate-secret

metallb:
  enabled: false
  namespace: metallb-system
  version: "v0.15.2
  default_addresses:
    - 10.10.90.100-10.10.90.110
  # reserved address must be explicity requested in the service definition
  reserved_addresses:
    - 10.10.90.120/30

traefik:
  enabled: false
  version: "36.3.0"
  namespace: traefik

longhorn:
  enabled: false
  version: "1.9.0"
  namespace: longhorn-system
  backup:
    location: "nfs://host.name:/export/path"
    secret: ""
  ingress:
    host: myhostname.mydomain
