# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metallb:
  enabled: false
  namespace: metallb-system
  version: "v0.14.5"
  # default-addresses can be auto assigned
  default_addresses:
    - 10.10.90.100-10.10.90.110
  # reserved address must be explicity requested in the service definition
  reserved_addresses:
    - 10.10.90.120/30

volsync:
  enabled: false
  namespace: volsync-system
  version: "0.9.1"
  endpoint: http://my.s3.provider:port/bucket
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

traefik:
  enabled: false
  version: "v27.0.0"
  namespace: traefik
  configPVC: traefik
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
  default_cert:
    main: main.host.name
#    sans:
#      - '*.main.host.name'
#      - "*.another.host.name"

longhorn:
  enabled: false
  version: "1.9.0"
  namespace: longhorn-system
  backup:
    location: "nfs://host.name:/export/path"
    secret: ""
  ingress:
    host: myhostname.mydomain