{{ if .Values.cert_manager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: {{ .Values.cert_manager.namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.cert_manager.cf_dns_api_token }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert_manager.issuer }}
  namespace: {{ .Values.cert_manager.namespace }}
spec:
  acme:
{{ if eq .Values.cert_manager.server "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{ else if eq .Values.cert_manager.server "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
{{ else }}
    server: {{ .Values.cert_manager.server }}
{{ end }}
    email: {{ .Values.cert_manager.cf_api_email }}
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
  namespace: default
spec:
  secretName: {{ .Values.cert_manager.default_certificate_secret }}
  issuerRef:
    name: {{ .Values.cert_manager.issuer }}
    kind: ClusterIssuer
  dnsNames: {{ .Values.cert_manager.default_domains }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces

{{ end }}
