{{ if .Values.cert_manager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.traefik.cf_api_email }}
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-credentials
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-certificate
spec:
  secretName: cluster-certificate-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: dev.stratolinux.io
  dnsNames:
  - dev.stratolinux.io
  - '*.dev.stratolinux.io'

{{ end }}
