{{ if .Values.traefik.enabled }}
{{ if .Values.traefik.default_cert.main }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.traefik.namespace }}
spec:
  defaultGeneratedCert:
    resolver: cloudflare
    domain:
      main: {{ .Values.traefik.default_cert.main | quote }}
{{- if .Values.traefik.default_cert.sans }}
      sans: [ "{{ join "\",\"" .Values.traefik.default_cert.sans }}" ]
{{ end }}
{{ end }}
{{ end }}