{{ if .Values.traefik.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.traefik.namespace }}
spec:
  defaultCertificate:
    secretName: {{ default-certificate-secret }}
{{ end }}
