{{ if .Values.metallb.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: {{ .Values.metallb.namespace }}
spec:
  autoAssign: true
  addresses:
  {{- range .Values.metallb.default_addresses }}
    - {{ . | quote }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: reserved-pool
  namespace: {{ .Values.metallb.namespace }}
spec:
  autoAssign: false
  addresses:
  {{- range .Values.metallb.reserved_addresses }}
    - {{ . | quote }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: {{ .Values.metallb.namespace }}

{{ end }}
