{{ if .Values.metallb.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: {{ .Values.metallb.namespace }}
spec:
  autoAssign: true
  addresses: {{ .Values.metallb.default-addresses }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: reserved-pool
  namespace: {{ .Values.metallb.namespace }}
spec:
  autoAssign: false
  addresses: {{ .Values.metallb.reserved-addresses }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: {{ .Values.metallb.namespace }}

{{ end }}
