{{ if .Values.cert_manager.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# cloudflare secret, used to generate certs
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
stringData:
  api-token: {{ .Values.traefik.cf_dns_api_token }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "{{ .Values.cert_manager.version }}"
    helm:
      valuesObject:
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


{{ end }}
