{{ if .Values.cert_manager.enabled }}
---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cert_manager.namespace }}
---
# cloudflare secret, used to generate certs
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: cloudflare-credentials
  namespace: {{ .Values.cert_manager.namespace }}
stringData:
  api-token: {{ .Values.cert_manager.cf_api_dns_token }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.cert_manager.namespace }}
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "{{ .Values.cert_manager.version }}"
    helm:
      valuesObject:
        crds:
          enabled: true
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

{{ end }}
