{{ if .Values.traefik.enabled }}
---
# namespace
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.traefik.namespace }}
---
# traefik helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.traefik.namespace }}
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: "{{ .Values.traefik.version }}"
    chart: traefik
    helm:
      valuesObject:
        service:
          annotations:
            metallb.io/loadBalancerIPs: {{ .Values.traefik.loadBalancerIP }}
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: {{ .Values.cert_manager.issuer }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

{{ end }}
