{{ if .Values.longhorn.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  # Add a finalizer to ensure that the application is deleted cleanly.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: {{ .Values.longhorn.version }} # It is recommended to pin to a specific chart version.
    helm:
      # Release name override
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        ingress:
          enabled: true
          host: {{ .Values.longhorn.ingress.host }}
        defaultBackupStore:
          backupTarget: nfs://rs822.internal.aceshome.com:/volume1/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.longhorn.namespace }}
  syncPolicy:
    automated:
      # Prune resources that are no longer in the git repository.
      prune: true
      # Allow Argo CD to delete resources that it did not create.
      selfHeal: true
    syncOptions:
      # Create the namespace if it does not exist.
      - CreateNamespace=true
  ignoreDifferences:
   - group: apiextensions.k8s.io
     name: engineimages.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: engines.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: instancemanagers.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: nodes.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: replicas.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: settings.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields
   - group: apiextensions.k8s.io
     name: volumes.longhorn.io
     kind: CustomResourceDefinition
     jsonPointers:
       - /spec/preserveUnknownFields

{{ end }}
