---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.metallb.namespace }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: {{ .Values.metallb.namespace }}
spec:
  addresses: {{ .Values.metallb.addresses }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: {{ .Values.metallb.namespace }}

