{{ if .Values.homepage.enabled }}
---
# config Replication Secret
{{ if .Values.replication.enabled }}
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: homepage-bucket-config
  namespace: {{ .Values.homepage.namespace }}
stringData:
  RESTIC_REPOSITORY: {{ .Values.replication.restic_repository }}/{{ .Values.homepage.namespace }}-homepage-config
  RESTIC_PASSWORD: {{ .Values.replication.restic_password }}
  AWS_ACCESS_KEY_ID: {{ .Values.replication.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.replication.aws_secret_access_key }}
{{ end }}
---
# config ReplicationDestination
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: homepage-config-replication-destination
  namespace: {{ .Values.homepage.namespace }}
spec:
  trigger:
    # manual restore
    manual: "seed-volume-from-backup"
  restic:
    # Name of the Secret with the connection information
    repository: homepage-bucket-config
    capacity: 5Gi
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
    accessModes:
      - ReadWriteOnce
{{ end }}
---
# config ReplicationSource
{{ if .Values.replication.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: homepage-config-replication-source
  namespace: {{ .Values.homepage.namespace }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ .Values.homepage.configPVC }}
  trigger:
    # Take a backup per cron schedule
    schedule: {{ .Values.homepage.replicationSchedule }}
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: homepage-bucket-config
    # Retention policy for backups
    retain:
      hourly: 2
      daily: 2
      weekly: 2
      monthly: 1
      yearly: 0
    # just in case it was locked
    unlock: unlock-me
    # Snap the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: ceph-block
{{ end }}
---
# config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.homepage.configPVC }}
  namespace: {{ .Values.homepage.namespace }}
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
{{ if .Values.replication.enabled }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: homepage-config-replication-destination
{{ end }}
  resources:
    requests:
      storage: 5Gi
---
# homepage helm chart application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.homepage.namespace }}
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: "3.1.0"
    chart: app-template
    helm:
      valuesObject:
        controllers:
          homepage:
            containers:
              app:
                image:
                  repository: {{ .Values.homepage.image }}
                  tag: {{ .Values.homepage.version }}
        service:
          app:
            controller: homepage
            ports:
              http:
                port: 3000
        ingress:
          app:
            enabled: {{ .Values.homepage.ingress.enabled }}
            hosts:
              - host: {{ .Values.homepage.ingress.host }}
                paths:
                  - path: /
                    pathType: Prefix
                    service: 
                      name: homepage
                      port: 3000
        persistence:
          config:
            enabled: true
            existingClaim: {{ .Values.homepage.configPVC }}
            globalMounts:
              - path: /app/config
        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}
