# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replication settings, identical for all services
replication:
  enabled: true
  restic_repository: "s3:http://minio.local:9000"
  restic_password: "restic_password"
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

# traefik
traefik:
  replicationSchedule: "0 * * * *"
  namespace: traefik
  configPVC: "traefik"
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
  defaultcert:
    main: main.host.name
    sans:
      - '*.main.host.name'
csismb:
  enabled: true
  username: user
  password: password
  share: smb.server.name/share
csinfs:
  enabled: true
  host: nfs.server.name
  share: /share
ceph:
  enabled: false
  namespace: rook-ceph
  dashPassword: myPassword
  ingress:
    host: myhostname.mydomain



