# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replication settings, identical for all services
replication:
  enabled: true
  restic_repository: "s3:http://minio.local:9000"
  restic_password: "restic_password"
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"

# traefik
traefik:
  replicationSchedule: "0 * * * *"
  namespace: traefik
  configPVC: "traefik"
  cf_api_email: "myemailaddress"
  cf_api_dns_token: "apitoken"
csi-smb:
  username: user
  password: password
  share: smb.server.name/share
ceph:
  namespace: rook-ceph
  dashPassword: myPassword
  ingress:
    host: myhostname.mydomain
metallb:
  namespace: metallb-system
  addresses:
    - 10.10.90.100-10.10.90.110
volsync:
  namespace: volsync-system
  endpoint: http://my.s3.provider:port/bucket


