{{ if .Values.coder.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.coder.namespace }}
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    chart: coder
    targetRevision: 2.12.1
    helm:
      valuesObject:
        coder:
          # You can specify any environment variables you'd like to pass to Coder
          # here. Coder consumes environment variables listed in
          # `coder server --help`, and these environment variables are also passed
          # to the workspace provisioner (so you can consume them in your Terraform
          # templates for auth keys etc.).
          #
          # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
          # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
          # they are already set by the Helm chart and will cause conflicts.
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  # You'll need to create a secret called coder-db-url with your
                  # Postgres connection URL like:
                  # postgres://coder:password@postgres:5432/coder?sslmode=disable
                  name: coder-db-url
                  key: url
            - name: CODER_EXTERNAL_AUTH_0_ID
              value: "stratolinux-coder"
            - name: CODER_EXTERNAL_AUTH_0_TYPE
              value: "github"
            - name: CODER_EXTERNAL_AUTH_0_CLIENT_ID
              value: "Iv23likAATfG3DwbaxJB"
            - name: CODER_EXTERNAL_AUTH_0_CLIENT_SECRET
              value: "60c5db84844f6f073b29b979a218766cd2baf97d"
            # (Optional) For production deployments the access URL should be set.
            # If you're just trying Coder, access the dashboard via the service IP.
            - name: CODER_ACCESS_URL
              value: "https://{{ .Values.coder.ingress.host }}"
          ingress:
            enable: {{ .Values.coder.ingress.enabled }}
            host: {{ .Values.coder.ingress.host }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: coder-db-url
  namespace: {{ .Values.coder.namespace }}
stringData:
  url: postgres://coder:coder@coder-db-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.coder.namespace }}
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.9
    helm:
      valuesObject:
        auth:
          username: "coder"
          password: "coder"
          database: "coder"
        persistence:
          size: "10Gi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}
