{{ if .Values.coder.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.coder.namespace }}
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitname/postgresql
    targetRevision: 15.5.9
    helm:
      valuesObject:
        auth:
          username: "coder"
          password: "coder"
          database: "coder"
        persistence:
          size: "10Gi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: coder-db-url
  namespace: {{ .Values.coder.namespace }}
stringData:
  url: postgres://coder:coder@coder-db-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable
{{ end }}
---