{{ if .Values.longhorn.enabled }}

apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: scheduled-backup
  namespace: longhorn-system
spec:
  cron: "0,30 * * * *"
  task: "backup"
  groups:
  - default
  retain: 5
  concurrency: 2

{{ end }}
